### PR TITLE
Fix slow zeroing of the buffer

### LINKED ISSUE #6: Bad performance after introducing zeroing of UninitSlice
After the following commit zeroing of UninitSlice completely dominates websocket CPU time:

```
commit 81d6b33c0607dec5f02418bab80cfbd88fa79b53
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Tue Dec 10 18:14:00 2019 +0200

    Fix UB in DoRead::read_from()
    
    We need to initialize the buffer first before creating a byte slice from
    it and passing it to Read::read().
```

It's very easy to reproduce by running the `server` example from `tungstenite-rs` and generating some websocket traffic (I've used websocat to send a large file via websocket):

```
tungstenite-rs [master●] % cargo build --release --example server           
    Finished release [optimized] target(s) in 0.02s
tungstenite-rs [master●] % perf record target/release/examples/server
```

```
websocat --binary readfile:/data/iso/cdrom_6.10.0.alpha1.iso  ws://127.0.0.1:3012/
```

The profile looks like this:
```
tungstenite-rs [master●] % perf report --percent-limit=1 | cat
# To display the perf.data header info, please use --header/--header-only options.
#
#
# Total Lost Samples: 0
#
# Samples: 15K of event 'cycles:u'
# Event count (approx.): 11805093888
#
# Overhead  Command  Shared Object       Symbol                                                                                                                        
# ........  .......  ..................  ..............................................................................................................................
#
    52.76%  server   server              [.] bytes::buf::uninit_slice::UninitSlice::write_byte
    37.22%  server   server              [.] input_buffer::DoRead::read_from
     7.31%  server   libc-2.33.so        [.] __memmove_avx_unaligned_erms
     1.45%  server   server              [.] tungstenite::protocol::WebSocket<Stream>::read_message


#
# (Tip: Show user configuration overrides: perf config --user --list)
#
```

It seems that the generated code is very suboptimal: it's writing zero bytes into the uninitialized buffer one byte at a time and thus causes a huge performance overhead in a websocket server.

### PR DESCRIPTION
**Pull request by daniel-abramov**
Fixes #6.

For context and explanation please check the comment: https://github.com/snapview/input_buffer/issues/6#issuecomment-870548303

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -162,8 +162,11 @@ impl<'t> DoRead<'t> {
             //
             // Read::read() might read uninitialized data otherwise, and generally creating
             // references to uninitialized data is UB.
-            for i in 0..data.len() {
-                data.write_byte(i, 0);
+            {
+                let memory_to_zero = data.as_mut_ptr();
+                for i in 0..data.len() {
+                    memory_to_zero.add(i).write(0);
```
Comment (strohel) [inline src/lib.rs:168]: This is interesting, my guess would be that `data.write_byte(i, 0)` would do pretty much the same thing as `data.as_mut_ptr().add(i).write(0)`?

Perhaps the compiler cannot see through the indirection and cannot optimize that? Perhaps it auto-vectorizes the new variant?

I've skimmed https://github.com/snapview/input_buffer/issues/6 but haven't quickly found explanation for this particular thing.

**Review by strohel — APPROVED** [review]
Looks good, I've added one curiosity question, but regardless of it I think this cannot hurt. So approving.

File: src/lib.rs (hunk 1 above)
Comment (strohel) [reply src/lib.rs:168]: Okay just found it, consider this resolved:
> The first big difference that I spotted is that it does not rely on write_byte(). The doc explicitly tells that the write_byte() will panic if index is out of range which in turn means that there is some boundary checking there (additional operation), apart from that I could not spot a significant difference.
>
> So I prepared a version of the input_buffer that does not use write_byte(), but instead calls to std::ptr::write(data.as_mut_ptr(), 0) or data.as_mut_ptr().write(0). To my surprise it did not really bring significant performance benefits, only minor improvements. I decided to move the data.as_mut_ptr() outside of the loop, so that I only call add(i).write(0) inside the loop and tested it. This change effectively brought huge performance benefit:

**Review by jxs — APPROVED** [review]

**Comment by jxs** [comment]
LGTM good job researching it Daniel :+1:

File: src/lib.rs (hunk 1 above)
Comment (gustav3d) [reply src/lib.rs:168]: does this make any difference ? 
on the method:
#[unroll_for_loops]

let len = data.len();
for i in 0..len {
  unsafe {ptr::write(memory_to_zero.add(i), 0); }  
}
